name: Print Hello World
on:
  push:
jobs:
  print: 
    runs-on: macOS-latest
    steps: npm test
      - name: Print Hello
        run: echo "Hello World"
    default:
      run:
        working-directory: backend
    steps:
      - name: Repo Clone
        uses: actions/checkout@v4
      - Install dependencies:
        run: npm ci
        
  second:
    runs-on: macOS-latest
    steps:
    - name: List Files
      run: ls

